CREATE DATABASE EShoppingDB;
GO
USE EShoppingDB;
GO

CREATE TABLE KHACH_HANG (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SoCMND VARCHAR(20),
    Email VARCHAR(100),
    TenDangNhap VARCHAR(50),
    MatKhau VARCHAR(255)
);

CREATE TABLE DON_HANG (
    SoDDH VARCHAR(20) PRIMARY KEY,
    MaKH INT FOREIGN KEY REFERENCES KHACH_HANG(MaKH),
    ThoiDiemDat DATETIME,
    LoaiPhieuGiao NVARCHAR(50),
    PhiGiaoHang DECIMAL(18,2),
    TongTriGia DECIMAL(18,2),
    HoTenNguoiNhan NVARCHAR(100),
    DiaChiNguoiNhan NVARCHAR(255)
);

CREATE TABLE THANH_TOAN (
    MaGiaoDich INT IDENTITY(1,1) PRIMARY KEY,
    SoDDH VARCHAR(20) FOREIGN KEY REFERENCES DON_HANG(SoDDH),
    LoaiThe VARCHAR(50),
    SoHieuTheAn VARCHAR(20), -- Đã che đi vì lý do an ninh
    TrangThai NVARCHAR(50)
);